### ISSUE TITLE
binary install path

### ISSUE THREAD

**Issue by frostworx** [laino/nicedaemon#1]
haven't tried it yet, but could be really nice. thanks a lot!
found a minor glitch: the Makefile installs the binary to  /usr/bin/
but the provided systemd servicefile has ExecStart=/bin/nicedaemon

I made a quick&dirty gentoo live ebuild (using /usr/bin/ for the binary) in case someone has some use for it:  https://bpaste.net/show/fa773f644873

**Comment by laino** [comment]
Whoops. Good catch.

I'm on arch where `/bin` is actually a symlink to `/usr/bin`.

**Comment by laino** [comment]
Fixed here: https://github.com/laino/nicedaemon/commit/3283d86053a27f2e5a525fd7a916e3fb1d400494
